FROM python:3.9-alpine

RUN pip3 install --upgrade pika redis jsonpickle requests pymysql pandas numpy matplotlib.pyplot seaborn scikit-learn re nltk gensim spacy operator spacy-lookups-data joblib gensim pickle
RUN python -m nltk.downloader punkt
RUN python -m spacy download en_core_web_sm

COPY worker-server.py /

COPY emoticon_dictionary1.pkl /
COPY lr_sentiment1.joblib /
COPY tfidf_sentiment.dictionary /
COPY tfidf_sentiment.model /
COPY topic_identification.py /
COPY topic_dictionary.pkl /
COPY tfidf.dictionary /
COPY topic_model1.model /
COPY topic_model1.model.expElogbeta.npy /
COPY topic_model1.model.id2word /
COPY topic_model1.model.state /
COPY topic_model1.model.state.sstats.npy /
COPY sentiment.py /
COPY preprocessing.py /
CMD python3 worker-server.py
