FROM python:3.9-alpine

RUN pip3 install --upgrade pika redis jsonpickle requests pymysql pandas numpy matplotlib.pyplot seaborn sklearn re nltk gensim spacy operator
RUN

COPY worker-server.py /

CMD python3 worker-server.py
