apiVersion: apps/v1
kind: Deployment
metadata:
        name: worker
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: rest-server
        template:
                metadata:
                        labels:
                                app: rest-server
                spec:
                        containers:
                        - name: worker
                          image: ihammes/worker:v1
                          imagePullPolicy: Always
